- admin/admin.go
- admin/pprof_test.go
This was originally from (`github.com/moov-io/admin/auth`](https://github.com/moov-io/auth/tree/bc111cf193d07b72c498ce2d62cdd605adacb31d/admin), but copied here for all projects.
> admin: create admin server

- http/server.go
Essentially, we want to be able to wrap InternalError inside other
functions in our apps, but the file-level information is nice to have.
Previously, the file information would be http.go:XX of the app, not
the route func we'd expect.
> http: fix callers for when nested inside other methods in apps

- http/response.go
- http/server.go
- http/server_test.go
Issue: https://github.com/moov-io/moov-io/issues/11
> http: simplify CORS, fix content-type bug

- time.go
- time_test.go
Issue: https://github.com/moov-io/base/issues/7
> time: still handle RFC3339 if provided

- time.go
- time_test.go
See: https://github.com/moov-io/banktime/issues/5
> time: adopt our BankTime methods onto Time

- CHANGELOG.md
- error.go
- error_test.go
- version.go
https://github.com/moov-io/base/issues/23
> Add parse error and error list

- error.go
> Additions for ACH

- error.go
- error_test.go
- version.go
> error: add Record and Line to ParseError.Error()

- http/bind/bind.go
See: https://github.com/moov-io/ofac
> http/bind: add ofac service

- k8s/kubernetes.go
- k8s/kubernetes_test.go
Realized this code is duplicated in several apps, see https://github.com/moov-io/ofac/pull/10 
Original: https://github.com/moov-io/paygate/blob/v0.2.0/pkg/achclient/client.go#L68-L72
> k8s: Add Inside func

- .travis.yml
- docker/docker.go
- docker/docker_test.go
Realized this code is duplicated in several apps, see https://github.com/moov-io/ofac/pull/10
> docker: add Enabled() bool

- http/bind/bind.go
See: https://github.com/moov-io/fed
> http/bind: add fed port bind

- admin/admin.go
- admin/admin_test.go
This can be used in apps for custom commands on the admin server.
See: https://github.com/moov-io/ofac/issues/9
> admin: add AddHandler to Server

- .travis.yml
- id.go
- id_test.go
Copied from https://github.com/moov-io/paygate/blob/v0.2.0/common.go#L145-L156
> Add ID() string instead of copying across projects

- admin/admin.go
- admin/health.go
- admin/health_test.go
Issue: https://github.com/moov-io/paygate/issues/50
> admin: add liveness and readiness checks to server

- http/bind/bind.go
Issue: https://github.com/moov-io/accounts/issues/44
> http/bind: rename gl to accounts

- http/response.go
- http/server.go
- http/server_test.go
- idempotent/idempotent.go
- idempotent/lru/lru.go
- time.go
I ran revive over this project and cleaned up the errors it reported.
> all: misc cleanup from linters

- .travis.yml
See: https://golang.org/doc/go1.13
> build: upgrade to Go 1.13

- .gitignore
- http/server.go
- http/server_test.go
Added a helper method GetSkipAndCount() to get skip and count params for resuse in pagination in Moov apis.
> Added GetSkipAndCount() for reuse in pagination

- go.mod
- go.sum
- log/context.go
- log/logger.go
- log/logger_test.go
- log/model_levels.go
Move logging package from `moov-io/identity`.
Renamed package from `logger` to `log`
Related issue: https://github.com/moov-io/identity/issues/60
> Add logging pkg from moov-io/identity

- database/migrator.go
Due to data race in https://github.com/golang-migrate/migrate we had to lock migration (and do not let to run them concurrently in our tests).
Thanks @vxio for this solution!
I'll release v0.14.1 after merge
> lock migration to avoid data race in migrate package

- CHANGELOG.md
this changelog is for https://github.com/moov-io/base/pull/119
> update changelog (v0.14.2) for sahring single MySQL container in tests

- log/logger_test.go
- log/model_valuer.go
> Add Strings() method

- log/logger_test.go
- log/model_valuer.go
If we don't have this, we have to do
```go
var nextRetry time.Time
if event.NextRetry != nil {
nextRetry = *event.NextRetry
}
```
> log: timeOrNil()

- .github/workflows/cgo.yml
- .github/workflows/nocgo.yml
- database/database.go
- database/database_cgo_test.go
- database/database_test.go
- database/error.go
- database/migrator.go
- database/model_config.go
- database/model_config_test.go
- database/mysql.go
- database/mysql_test.go
- database/sqlite_cgo.go
- database/sqlite_cgo_test.go
- database/sqlite_nocgo.go
- database/tx.go
- go.sum
Issue: https://linear.app/moov/issue/INFRA-327/spike-investigate-a-new-moov-iomoovfinancial-base-docker-image
> INFRA-327 database: support disabling CGO 

- log/logger.go
- log/logger_impl.go
- log/logger_test.go
- log/model_levels.go
Add a debug level to our logging
> add debug level

- CHANGELOG.md
Added changelog entry for improvements to log library
ref #180
> upd changelog for previously merged #180

- log/logger_test.go
- log/model_valuer.go
- Add int64 valuer for logging
> add int64 valuer

- database/database_cgo_test.go
- database/mysql_test.go
- go.mod
- go.sum
- build: update github.com/mitchellh/mapstructure to v1.4.3
- database: close sql test resources
> fix: linter fixup and update mapstructure 

- database/database.go
Fixing a minor copy/paste flub.
> database: Fix ApplyConnectionsConfig

- database/mysql.go
- database/mysql_test.go
- go.sum
Adding in additional metrics to track for database connections
> Adding in additional metrics to track for database connections

- database/mysql.go
- database/mysql_test.go
Referencing the db and the metrics was causing a race condition that was just recently discovered. This fixes the issue where I discovered it.
> Fix status race

- database/spanner.go
- migrations/002_create_tests.up.spanner.sql
Adding in comment cleaning for the spanner migrations
> Adding in comment cleaning for the spanner migrations

- log/logger_impl.go
Adding in the ability to specify with env variables how to format the log lines
> Adding in the ability to specify with env variables how to format the log lines

- database/migrator.go
When going back through logs, it would be helpful to see the DB version at a specific migration. This has come up when looking into issues with past migrations which were found to be faulty at a later point in time.
Basically, this just adds the current and new versions to the existing logging along with the clean/dirty flag.
> Add better logging around DB migrations

- database/database.go
- database/database_test.go
- database/mysql.go
- database/postgres.go
- Catch psql deadlock error and return in helper `database.DeadlockFound()`
> catch psql deadlock err
