moov-io/base

http/server.go, http/server_test.go, idempotent/idempotent.go, idempotent/idempotent_test.go
We aren't creating ID's longer than this limit so there's no reason to allow them. 36 characters is length of a UUID.
The default limit in Go is something like 10k characters, but we don't want those filling up log files.
=> http: enforce max header lengh of 36 UTF-8 characters

http/doc.go, http/response.go, http/response_test.go, http/server.go, idempotent/idempotent.go, idempotent/idempotent_test.go, idempotent/lru/lru.go, idempotent/lru/lru_test.go
This is a wrapper around http.ResponseWriter that optionally:
- records response timings in a go-kit Histogram
- emits a log line with request/response information iff X-Request-ID != ""
- optionally 403's if X-User-Id isn't set
Fixes: https://github.com/moov-io/base/issues/3
=> http: add ResponseWriter from auth and paygate projects

http/response.go
`FromRequest` already marks the key as seen, so we don't need to double count.
=> http: don't double record idempotency key

time.go, time_test.go
```Go
now := Now()
fmt.Println(start.Sub(now.Time))
```
=> time: Add NewTime for wrapping time.Time

time.go, time_test.go
Reverts https://github.com/moov-io/base/pull/28 and the timezone changes.
=> time: convert new and incoming times (JSON) to UTC rather than America/New_York

time.go, time_test.go
For https://github.com/moov-io/ach/issues/556 we're going to expose the format to allow ACH to parse.
=> time: expose ISO 8601 format

admin/admin.go, admin/admin_test.go
Paygate tests are failing due to race conditions between tests grabbing ports via admin.NewServer, so let's keep it alive as unix systems pick the port atomically.
=> admin: keep net.Listener alive with random port discovery

time_test.go
July 4th 2021 falls on a Sunday, so it's a perfect test case for this.
```
$ cal 07 2021 
July 2021        
Su Mo Tu We Th Fr Sa  
1  2  3  
4  5  6  7  8  9 10  
11 12 13 14 15 16 17  
18 19 20 21 22 23 24  
25 26 27 28 29 30 31 
```
=> time: add a specific test for sunday federal holidays

stime/static_time.go, stime/system_time.go
I suggest we rename `stime` to `timetest` to indicate that this package should only be used in testing; similar to `net/httptest`. Let me know what you think.
Related issue https://github.com/moov-io/identity/issues/60
=> add stime pkg from moov-io/identity`

log/logger.go, log/logger_test.go
at least I need this change to replace go-kit/log with base/log here: https://github.com/moov-io/base/blob/master/http/response.go#L61
=> accept variable number of key, val in log.WithKeyValue

log/logger.go, log/logger_test.go
Reverts moov-io/base#92
Motivation for this revert is to reduce the chance of passing wrong amount of arguments to the method and getting broken logs. As example,
```go
log.WithKeyValue("one", "1", "two", "2", "three", "3")
```
Say you miss the "1" in that line and now your indexes are all off. You'd end up with "one=two" "2=three" in logs. 
Versus with fixed number of arguments (this PR) you are constrainted by the compiler to not mess it up:
```go
log.WithKeyValue("one", "1").WithKeyValue("two", "2")
```
Also, if you try to add 3 like this:
```go
log.WithKeyValue("three", ) 
```
it would compiler error.
Based on discussion with @InfernoJJ
=> Revert "accept variable number of key, val in log.WithKeyValue"

log/context.go, log/logger.go, log/logger_impl.go, log/logger_test.go, log/model_stacktrace.go
Added methods:
- `logger.Log(msg string)` which calls `logger.Logf(format string, args ...string)`
- `logger.LogError(err error) error` which calls `logger.LogErrorf(format string, args ...string)`
And moved interfaces and helper items to `logger.go` file to simplify package layout.
=> refactor logging package and add helpers

config/config.go, database/migrator.go, log/logger.go, log/logger_impl.go, log/logger_test.go
In our previous implementation:
```go
// causes linter warning 
logger.LogError(err)
// Using a blank identifier is awkward and may set off linter warnings because it's still ignoring the error
_ = logger.LogError(err)
```
So having `logger.LogError()` return a custom struct, `LoggedError`, that holds the error allows us to do
```go
logger.LogError(err) // no linter warning!
or
if err != nil {
return logger.LogError(err).Err() // inlined
}
```
=> Set LogError() and LogErrorf() to return LoggedError struct instead of error

database/database.go, database/database_test.go, database/migrator.go, database/model_config.go, database/mysql.go, database/mysql_test.go, database/sqlite.go, database/sqlite_test.go, migrations/001_create_tests.up.sql
This PR fixes 2 issues in base/database (which afaik is not used in other projects yet).
1. incorrect configuration of migration path
Expected behavior:
I can configure path to migrations files in `DatabaseConfig.migrationsDir` and they will be loaded from there during the migration
Actual behavior:
* There is no way to configure migrationsDir
* migrationsDir should be a module path (absolute path starting from the module root) and can't be treated as OS path. here is why:
Short: To embed migration files into binary we use [pkger](https://github.com/markbates/pkger/). `migrationsDir` can't be read by Pkger as Pkger uses static analysis and walks the AST of our application to find certain declarations such as pkger.Include and others. Because of this it can’t determine dynamic runtime …
=> Database fixes

CHANGELOG.md, database/sqlite.go
With the latest changes when we use two separate DB connections for the service and for migrations a bug was introduced. SQLite helper (CreateTestSqliteDB) didn't use proper path of SQLite DB file for migrations. This PR fixes this bug.
=> Fix test sqlite db helper

log/logger_impl.go, log/logger_test.go
All logs would have a key-value pair like `time=2020-10-20T05:09:49Z` in `UTC`
Fixes #109
=> Add timestamp field to all logs

database/database.go, database/database_test.go, database/error.go, database/model_config.go, database/mysql.go, database/sqlite.go, database/sqlite_test.go
- Removed global var `InMemorySqliteConfig` to avoid incorrect usage in tests; all services should call `CreateTestSQLiteDB()` for testing with sqlite
- Renamed instances of `Sqlite` to `SQLite`
- Improved tests to check proper behavior
=> remove global var InMemorySQLite and minor refactor

go.sum, http/response.go, http/response_test.go, log/logger.go, log/logger_impl.go, log/logger_test.go, log/model_fields.go, log/model_levels.go, log/model_stacktrace.go
1. log: Add Send() to Logger API
In some cases, you'll want to log an event without providing a message. For example, in `http/response.go:62`:
```go
w.log.With(log.Fields{
"method":    w.request.Method,
"path":      w.request.URL.Path,
"status":    code,
"duration":  diff,
"requestID": requestID,
}).Send()
```
In this case, `Send()` just calls `Log("")` implicitly; this is similar to [zerolog's implementation](https://godoc.org/github.com/rs/zerolog#Event.Send)
2. log: Set Context value types from `string` to `interface{}`, fixes #110
Our logger implementation calls  [writeValue](https://github.com/go-logfmt/logfmt/blob/master/encode.go#L197) which will properly encode a value to the underlying `io.Writer`. This let's us do the following without having to cast the value to a string: …
=> log/http: Update Logger API and http to use base/log

.github/workflows/mysql-volumeless.yml, database/database_test.go, database/mysql.go, database/mysql_test.go, go.mod, go.sum, mysql/Dockerfile, mysql/README.md, mysql/makefile, mysql/test-mysql-is-ready.sh
@adamdecaf @vxio 
With this change:
1. We run single MySQL container that all tests use
2. Each test that calls `db := CreateTestMySQLDB` gets own unique database. On `db.Close()`database is dropped.
3. We don't stop / remove MySQL container as we don't know when all out tests are done
Using this changes reduces tests time for
* Customer's from 2m:30s to 28s (on my machine)
* Paygate's  from to 1m:10s to 30s (on my machine)
=> database: optimize testing by sharing one mysql container

.github/CODEOWNERS, config/config.go, http/response.go, log/logger.go, log/logger_impl.go, log/logger_test.go, log/model_fields.go, log/model_formats.go, log/model_levels.go, log/model_stacktrace.go, log/model_valuer.go
Remove the interface{} from being a valid argument when deep down go-kit can error out.
=> Remove the interface{} from being a valid argument when deep down go-kit can error out.

api/common.yaml
This Error type is used in every API endpoint and so it was a bit
unclear and messy when looking at endpoints that don't really validate
fields. Instead let's use explicit filler text.
=> api: use a clearer default error example

go.sum, log/logger_test.go, log/model_valuer.go
With this, we won't have to write something like:
```go
if event.OrganizationID != nil {
logger.Set("organizationID", log.String(*event.OrganizationID))
} else {
logger.Set("organizationID", log.String("null"))
}
```
=> stringOrNil valuer

time.go, time_test.go
Allowing a timezone to be passed to `Now`. This is important since `IsBankingDay` and `IsWeekend` are timezone specific.
=> Allow timezone to be passed to time Now

database/mysql.go, database/mysql_test.go, go.sum
We need to ensure data inserted matches the column definitions and if
not to treat that as a bug.
See: https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-strict
=> database: set STRICT_ALL_TABLES on mysql connections

log/logger_impl.go
Adding in a .Nil() method to the logged error so you can log and return nil in the same oneliner
=> Adding in a .Nil() method to the logged error

admin/admin.go, admin/admin_test.go
This PR adds a function to the `Server` struct that creates a path prefixed subrouter. This enables users to use different middlewares for different route groups.
=> add subrouter function to Server

database/model_config.go, database/model_config_test.go, mask/password.go, mask/password_test.go
This is useful to hide passwords with `GET /config` on admin servers.
=> database: mask mysql password in JSON marshaling

time.go, time_test.go
PayGate Version: `0.10.3`
**What were you trying to do?**
Coming from Paygate, the Effective Entry Date of an ACH entry was not calculated properly over weekends and was caught by Bank Validations
related: https://github.com/moov-io/paygate/pull/644
**What did you expect to see?**
Given any friday
`t.AddBankingDay(2)` adds 2 banking days to given date (monday, tuesday) and should return tuesday
**What did you see?**
`t.AddBankingDay(2)` adds 2 days to given date and if the date is still a holiday it adds 1 banking day recursively
This means the code doesnt check if the first added day is banking day or not
**How can we reproduce the problem?**
added failing test cases
=> unexpected behaviour AddBankingDay

database/database.go, database/model_config.go, database/model_config_test.go, database/mysql.go, database/mysql_test.go
I left the test as-is owing to the fact that connecting to the official MySQL Docker container via TLS [is a rather involved process](https://techsparx.com/software-development/docker/damp/mysql-ssl-connection.html) and I'm mostly just trying to get a proof-of-concept going here.
=> database: Add MySQL SSL CA file config option

database/mysql.go
Add `multiStatement=true` to allow for multiple statements in a single migration file
=> Allow multiple statements in a single migration file

database/pkger.go
What:
* handle (do not ignore) error from the function that adds migration files into `pkger`
Why:
Currently, we ignore the error when pkger walks the migration directory and the migration file name does not match the expected format.  When such happens it stops adding the rest of the files. In our case with manual migrations, we named the file in a way so [golang-migrate](https://github.com/golang-migrate/migrate) will ignore it: we just removed `.up` part. But, we didn't know that we have one more layer of file format checking :( 
P.S. we should not check file name format here and delegate it to [golang-migrate](https://github.com/golang-migrate/migrate/blob/511ae9f5b6bea5190b340243169359455281458b/source/parse.go#L21)
=> do not ignore error when walk dir in pkger

log/logger_impl.go
Often it's helpful to 'go test ./... -v' and get more data. This
is a handy helper method to switch between stdout and discard logging.
=> log: add a helper for stdout logging during verbose test runs

log/logger_impl.go, log/model_valuer_test.go
We've been seeing panics within our logging framework when `Context()` calls panic. Let's avoid these and record when they occur. 
```
=== RUN   TestValuer__String
level=error file=/Users/adam/code/src/github.com/moov-io/base/log/model_valuer_test.go line=20 msg="recovered from runtime.errorString - runtime error: invalid memory address or nil pointer dereference"
ts=2022-06-15T20:59:32Z msg="shouldn't panic" level=info
--- PASS: TestValuer__String (0.00s)
```
=> fix: recover from panics during logging, log those if we can

time.go, time_test.go
We can easily run into conversion issues when switching between UTC and EST. Let's allow our caller to specify the location when they call `NewTime`.
=> fix: quit converting times to UTC

config/config.go, config/config_test.go
Previously it was causing issues with merging arrays where if the new array being merged wasn't bigger than the old one values would stick around. This hopefully fixes that
=> config: overwrite slices instead of merging

database/spanner.go, database/spanner_test.go
Changes:
* Similar to what we support for `mysql::MySQLUniqueViolation`, added `spanner::SpannerUniqueViolation` that look at the error code or message to deduce if we have a duplicate error. 
Note: `spanner.Error` will be deprecated in the future, replaced with `APIError`. I added tests for both responses from client.
=> add similar unique violation check as sql for spanner

database/mysql.go, database/spanner.go
- Add `MySQLDeadlockFound()` method to detect mysql deadlock found errors
- Update existing error handling methods to check for nil and avoid nil pointer exceptions
=> detect mysql deadlock err

http/server.go, http/server_test.go
adding the `orderBy` param that way it's reusable and consistent if/when we add new endpoints that use ordering. this is [similar to how we handle paging](https://github.com/moov-io/base/blob/master/http/server.go#L122).
=> add orderBy param

log/model_valuer.go, log/model_valuer_test.go
- Prevent panic when calling `log.Stringer(nil)`
=> Check nil on fmt stringer

time.go, time_test.go
```go
// AddBankingTime increments t by the hours, minutes, and seconds provided
// but keeps the final time within 9am to 5pm in t's Location.
func (t Time) AddBankingTime(hours, minutes, seconds int) Time 
```
=> feat: AddBankingTime

database/database.go
https://github.com/golang/go/issues/45993#issuecomment-1427873850
Tested this by setting the following configs 
`MaxLifetime: 1000s
MaxIdleTime: 3s`
and following code 
```
stats := env.DB.Stats()
fmt.Println("Open connections", stats.OpenConnections, "Idle connections", stats.Idle)
fmt.Println("Sleep")
// Should be long enough to clear idle connection
time.Sleep(5 * time.Second)
stats = env.DB.Stats()
fmt.Println("Open connections", stats.OpenConnections, "Idle connections", stats.Idle)
```
Before change:
```
Open connections 1 Idle connections 1
Sleep
Open connections 1 Idle connections 1
```
After change:
```
Open connections 1 Idle connections 1
Sleep
Open connections 0 Idle connections 0
```
=> Testing known github issue

database/model_config.go, database/spanner.go, go.mod, go.sum
Spanner migrations clean statements doesn't support all features and is a bit aggressive and needs to be able to shut off in specific cases.
Clean statements in migrate allow for comments and multi-statements in one file, but does this by parsing and rewriting the migration files.
=> Make the spanner migrations clean statements configurable.

config/config.go, config/config_test.go, config/testdata/with-regexp.yml
This has come up once or twice where it'd be nice to specify a regex in the config as a string.
=> feat: allow config to unmarshal regexes as strings

log/README.md, log/struct_context.go, log/struct_context_test.go
Add the `StructContext` function that allows to log struct fields automatically by using tags.
```go
import "github.com/moov-io/base/log"
// Define a struct with log tags
type User struct {
ID       int    `log:"id"`
Username string `log:"username"`
Email    string `log:"email,omitempty"` // won't be logged if empty
Address  Address `log:"address"` // nested struct must have log tag
Hidden   string // no log tag, won't be logged
}
//...
// Log with struct context
logger.With(log.StructContext(user)).Info().Log("User logged in")
```
=> Add struct context

ratex/ratelimit.go, ratex/ratelimit_test.go, sql/sql_test.go
Use "attempts" for MaxAttempts and AttemptNum to clarify that the count includes the initial try and subsequent retries - i.e. a MaxAttempts of 3 is 1 try with 2 possible retries.
BREAKING CHANGE: renames MaxRetries -> MaxAttempts, RetryAttempt -> AttemptNum
=> refactor!: clarify variable naming for attempts in retryable operations
